title: Stardust Science
description: A Sample-based, Perceptually- and Cognitively-driven Visual Analysis of Massive Scientific Data Using an Asynchronous Tasking Engine 
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
